### ISSUE TITLE
Missing :sweet_xml in applications

### ISSUE THREAD

**Issue by sebn** [marceldegraaf/ueberauth_cas#12]
Hello there!

First, thank you for ueberauth_cas ❤️

Unless I'm mistaken, `:sweet_xml` is missing from `:applications` list in `UeberauthCAS.Mixfile.application`. It may still work in local dev thanks to mix inference, but fail once deployed in production without it (in my case using distillery).

Possible solutions:

1. Add it, e.g. `applications: [:logger, :ueberauth, :httpoison, :sweet_xml]`. The downside is that next time we add another dependency, we may forget to add it to `:applications`.
2. Remove `:applications` to let mix populate it automatically from `deps/0` (possibly supported since Elixir 1.5 or 1.6? I'm not sure) and put the non-depency apps into the `:extra_applications` instead, e.g. `extra_applications: [:logger]`. The downside is that it may not support older Elixir versions anymore.

I would favor the latter, but I don't know whether the Elixir version is a concern.

I'd like to make a PR but I'm a bit overwhelmed right not.
Hope this still helps!
Thanks

**Comment by niknetniko** [comment]
The min Elixir version is 1.8, so that wouldn't be a problem.

I think you're right in saying the `:applications`  key can be removed. I don't think `:extra_applications` is actually necessary, since we don't use `logger`, but I'd have to check the code to be sure.
